# Change these first
owner: xiotzsupport # Your GitHub organization or username, where this repository lives
repo: xIoTz-Uptime # The name of this repository

sites:

#  - name: "00_Uptime_Dashboards"
#    url: https://dashboards.xiotz.com/

  - name: "000_Uptime_FreshPing"
    url: https://statuspage.freshping.io/69684-xIoTzUCAP 
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302


  - name: "000_Uptime_xIoTzUCAP"
    url: https://github.com/xiotzsupport/xIoTz-Uptime
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "000_Uptime_xIoTzCX"
    url: https://github.com/xiotzsupport/xIoTzcs-Uptime
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "01_UCAP_India_MilanLabs"
    url: https://milanlabs-endpoint.xiotz.com/app/login? 
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "02_UCAP_India_Internal_CyberAudit"
    url: https://cyberaudit-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302


  - name: "03_UCAP_India_Internal_Zenalyst"
    url: https://zenalystai-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302


  - name: "04_UCAP_India_Internal_XAR"
    url: https://xar-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302


  - name: "04_UCAP_India_Internal_XAR"
    url: https://xar-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302


  - name: "05_UCAP_India_Internal_UppgradeAI"
    url: https://upgradeai-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302



#alabeer
  - name: "06_UCAP_India_OneXtel_SBI"
    url: https://sbionextel-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "07_UCAP_India_OneXtel_OP"
    url: https://onextel-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "08_UCAP_India_OneXtel_NSE"
    url: https://onextelnse-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
  - name: "09_UCAP_India_OneXtel_DC"
    url: https://onextelserver-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "10_UCAP_India_OneXtel_WP"
    url: https://waonextel-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302

  - name: "12_UCAP_India_ITI-Finance"
    url: https://itifinance-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302

  - name: "13_UCAP_India_FourDimensions"
    url: https://fourdimensions-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
   
  - name: "21_UCAP_UAE_Medseven"
    url: https://medseven-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
	  
  - name: "22_UCAP_UAE_Cicon"
    url: https://cicon-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "23_UCAP_UAE_ALOmeria"
    url: https://alomeria-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
	  
  - name: "24_UCAP_UAE_AlphaSeven"
    url: https://alphaseven-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "31_UCAP_India_U360_Dovetail"
    url: https://dovetail-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
	  
  - name: "32_UCAP_India_U360_Himedia"
    url: https://himedia-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
	  
  - name: "33_UCAP_India_U360_JLMorison"
    url: https://jlmorison-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
	  
  - name: "34_xIoTz_UCAP_India_U360_Unishield"
    url: https://unishield-endpoint.xiotz.com/app/login?
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
	  
  - name: "41_UCAP_Tanzania_FlashNet"
    url: https://flashnet-endpoint.xiotz.com/app/login?
    __dangerous__disable_verify_peer: true
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302

# xIoTz ECLOUDS

# Looks like removeed 
#  - name: "ecloud-lynas.xiotz.com"
#    url: https://ecloud-lynas.xiotz.com/

  - name: "ecloud-ict.xiotz.com"
    url: "https://ecloud-india-dovetail.xiotz.com/"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 204
      - 301
      - 302
      - 303
      - 307


  - name: "ecloud-india-ho-serverroone.xiotz.com"
    url: https://ecloud-india-ho-serverroone.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303
	  
  - name: "ecloud-india-ho-serverroprod.xiotz.com"
    url: https://ecloud-india-ho-serverroprod.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303

  - name: "ecloud-india-ho-serverrothree.xiotz.com"
    url: https://ecloud-india-ho-serverrothree.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303
	  
  - name: "ecloud-india-ho-serverrotwo.xiotz.com"
    url: https://ecloud-india-ho-serverrotwo.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303

 # UCAP milan connectivity is working fine, Need to scan for Ecloud port and check if we can login 
 # !!! Ecloud infomration needs to be manually copied and stored in GIT
  - name: "ecloud-india-milan.xiotz.com"
    url: https://ecloud-india-milan.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303

  - name: "ecloud-india-rd-alphard.xiotz.com"
    url: https://ecloud-india-rd-alphard.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303

  - name: "ecloud-india-rd-betard.xiotz.com"
    url: https://ecloud-india-rd-betard.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303
	
  - name: "ecloud-india-rd-deltard.xiotz.com"
    url: https://ecloud-india-rd-deltard.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303
   
  - name: "ecloud-india-rd-sigmard.xiotz.com"
    url: https://ecloud-india-rd-sigmard.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 204
      - 307
      - 303
	  
  - name: "ecloud-uae-alomeira.xiotz.com"
    url: https://ecloud-uae-alomeira.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
  - name: "ecloud-uae-alpha7.xiotz.com"
    url: https://ecloud-uae-alpha7.xiotz.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      
# Ecloud CICON
#  - name: "ecloud-uae-cicon.xiotz.com"
#    url: https://ecloud-uae-cicon.xiotz.com/
	      
# NEed to Revisit @Rohit
  - name: "ecloud-uae-medseven.xiotz.com"
    url: https://ecloud-uae-medseven.xiotz.com/
    maxResponseTime: 5000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: Status-UCAP.xiotz.com
  #baseUrl: /xIoTz-Uptime
  logoUrl: https://raw.githubusercontent.com/xiotzsupport/xIoTz-Uptime/refs/heads/master/upptime-icon.svg
  name: xIoTz UCAP Monitor
  introTitle: "xIoTz Uptime Monitoring."
  introMessage: xIoTz Websites Uptime monitoring
  navbar:
    - title: xIoTz UCAP Status - Monitor
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
