# Change these first
owner: xiotzsupport # Your GitHub organization or username, where this repository lives
repo: xIoTz-Uptime # The name of this repository

sites:


  - name: "01_India_MilanLabs"
    url: https://milan.xiotz.com/  
    
  - name: "02_India_CyberAudit"
    url: https://cyberaudit.xiotz.com/

  - name: "04_India_Jesons"
    url: https://xoc-jesonsxoc.xiotz.com/
    
  - name: "05_India_TDAC"
    url: https://tdac.xiotz.com/
    
  - name: "06_India_SISN"
    url: https://sisn.xiotz.com/
    
  - name: "07_India_OneXtel_OP"
    url: https://onextel.xiotz.com/
    
  - name: "08_India_OneXtel_NSE"
    url: https://onextelnse.xiotz.com/
    
  - name: "09_India_OneXtel_DC"
    url: https://onextelserver.xiotz.com/
    
  - name: "10_India_SyrmaSGS"
    url: https://syrmasgs.xiotz.com/
    
  - name: "11_UAE_Medseven"
    url: https://medseven.xiotz.com/
    
  - name: "12_UAE_Cicon"
    url: https://xoc-cicon.xiotz.com/
    
  - name: "13_UAE_ALOmeria"
    url: https://xoc-alomeria.xiotz.com/
    
  - name: "14_UAE_AlphaSeven"
    url: https://alphaseven.xiotz.com/
    
  - name: "15_UAE_Gemini"
    url: https://xoc-geminiuae.xiotz.com/
    
  - name: "16_UAE_Bell"
    url: https://xoc-bell.xiotz.com/
    
  - name: "21_Australia_CornellDieselSystems"
    url: https://cornell.xiotz.com/
    
  - name: "22_Australia_MTQ-Cornell"
    url: https://mtq.xiotz.com/
    
  - name: "23_Australia_CDMLogistics"
    url: https://cdmlogistics.xiotz.com/

   #id: "WEB024"
  - name: "24_Australia_PrimaryComms"
    url: https://primarycomms.xiotz.com/
    
  - name: "25_Australia_NIA"
    url: https://nia.xiotz.com/
    
  - name: "26_Australia_Thomax"
    url: https://thomaxxoc.xiotz.com/

  - name: "27_Australia_ICT"
    url: https://ict.xiotz.com/

  - name: "31_India_Dovetail"
    url: https://dovetail.xiotz.com/

  - name: "32_India_Himedia"
    url: https://himedia.xiotz.com/
    
  - name: "33_India_JLMorison"
    url: https://jlmorison.xiotz.com/
    
  - name: "34_xIoTz_India_Unishield"
    url: https://unishield.xiotz.com/

  - name: "35_India_UnishieldCx"
    url: https://unishieldcx.xiotz.com/

  - name: "36_India_Indevia"
    url: https://indeviaucap.xiotz.com/

  - name: "41_Tanzania_FlashNet"
    url: https://flashnet.xiotz.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /xIoTz-Uptime
  logoUrl: https://raw.githubusercontent.com/xiotzsupport/xIoTz-Uptime/refs/heads/master/upptime-icon.svg
  name: Upptime
  introTitle: "xIoTz Uptime Monitoring."
  introMessage: xIoTz Websites Uptime monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
